# The configuration file should be in yaml-format (as here) or in json
# format. when read into the Snakefile as follows:
#     configfile: "mappingConfig.yaml"
# the syntax creates a nested dictionary and the variables defined
# below can be accessed in the Snakefile rules, e.g.,
#   - config["reference"] expands introduction "/path/to/ExampleData/reference/Mus_musculus.GRCm38.dna.chromosome.19.fa.gz"

reference: /path/to/ExampleData/reference/Mus_musculus.GRCm38.dna.chromosome.19.fa.gz
annotation: /path/to/ExampleData/annotation/Mus_musculus.GRCm38.99.chromosome.19.gtf.gz
